import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
// (1/2) 방금 수정한 ThemeProvider를 import 합니다.
import { ThemeProvider } from "@/components/theme-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "My Diary App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // (2/2) <html> 태그에 suppressHydrationWarning을 추가하고
    // <body>를 ThemeProvider로 감싸줍니다.
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}